### PR TITLE
Add Joplin by @chrisbeardy

### PR DESCRIPTION
**Pull request by luxonauta**

### CODE REVIEW

**Comment by zenorocha** [comment]
@domgoodwin if you want to make a dummy commit on https://github.com/dracula/joplin your name will show up on the website: https://draculatheme.com/joplin

**Comment by domgoodwin** [comment]
Thanks @zenorocha @luxonauta 
PR here: https://github.com/dracula/joplin/pull/2

**Comment by zenorocha** [comment]
@domgoodwin looks like the dummy commit didn't work because there were 0 changes. Can you make another commit adding an extra break line to the README or something silly like that?

CleanShot 2022-01-27 at 21 26 47@2x

**Comment by domgoodwin** [comment]
https://github.com/dracula/joplin/pull/3
Take 2

**Pull request merged**
