### PR TITLE
Add Code::Blocks by @wasi-master

### PR DESCRIPTION
**Pull request by luxonauta**

### CODE REVIEW

**Comment by zenorocha** [comment]
Thanks @luxonauta!

**Comment by wasi-master** [comment]
So the site should be up now right?

**Comment by luxonauta** [comment]
> So the page should be up and running now right?

Yes, soon it's online! 😅

**Comment by zenorocha** [comment]
boom! it's live! 💥 

https://draculatheme.com/codeblocks

thanks for your patience @wasi-master ;)

**Comment by wasi-master** [comment]
Thanks for your cooperation :)

**Pull request merged**
